### ISSUE TITLE
Rename Purchasable to something more fitting.

### ISSUE THREAD

**Issue by BenMorganIO** [spurryal/spur#24]
Not everything that people buy is purchasable. Is a rental purchasable? Nope.

What I'm thinking:

- `Payable`
- `Sellable`
- `Aquirable`
- `Buyable`

**Comment by hickscorp** [comment]
Actually, I think `Purchasable` is good. Your mistake is to ask if a rental is purchasable, it's not. But the product is not a rental! The product is a rental deal. A rental deal is totally purchasable :) Well you see the point.

**Comment by BenMorganIO** [comment]
@hickscorp you have set my mind to rest.
